name: Deploy a Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Instalar Surge
      run: npm install -g surge

    - name: Desplegar en Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: |
        surge --project ./ --domain angelmiguel-prueba.surge.sh --token $SURGE_TOKEN
